config/routes.rb
Rails.application.routes.draw do
	root :to => 'posts#top'
	get 'index' => 'posts#index'
	get 'posts' => 'posts#index'
	post 'posts/:id' => 'posts#show', as: 'post'
    delete 'posts/:id' => 'posts#destroy', as: 'destroy_post'
	resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def top
    end

    def index
        @post = Post.new
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def create
  	    post = Post.new(post_params)
  	    post.save
  	    redirect_to post_path(post.id)
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        post.update(post_params)
        redirect_to post_path(post.id)
    end

    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to posts_path
    end

    private

    def post_params
  	    params.require(:post).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
	<head>
		<mata charset = "UTF-8">
		<title> 4-8</title>
		<%= stylesheet_link_tag "application", :media => "all" %>
	</head>

	<body>
		<h1> Editing Book</h1>
		<%= form_for(@post) do |f| %>

    	<h4 class="form_field"> Title</h4>
    	<%= f.text_field :title, class: "book_title" %>

    	<h4 class="form_field"> Body</h4>
    	<%= f.text_area :body, class: "book_body" %>

    	<br><%= f.submit 'Update Book' %>
		<% end %>

		<%= link_to "Show", post_path(@post.id), class: "show_#{@post.id}" %> |
		<%= link_to "Back", posts_path(@post.id), class: "back" %>
	</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<mata charset = "UTF-8">
		<title> 4-8</title>
		<%= stylesheet_link_tag "application", :media => "all" %>
	</head>

	<body>
		<h1>Books</h1>

			<table>
				<thead>
					<tr>
						<th>title</th>
						<th>body</th>
						<th></th>
					</tr>
				</thead>

			<tbody>
				<% @posts.each do |post| %>
					<tr>
						<td>
							<%= post.title %>
						</td>
						<td>
							<%= post.body %>
						</td>
						<td>
							<%= link_to "Show", post_path(post.id), class:"show_#{post.id}" %>
							<%= link_to "Edit", edit_post_path(post.id), class:"edit_#{post.id}" %>
							<%= link_to "Destroy", destroy_post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"destroy_#{post.id}" %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>

		<h2> New book</h2>

			<%= form_for(@post) do |f| %>

    			<h4 class="form_field"> Title</h4>
    			<%= f.text_field :title, class: "book_title" %>

    			<h4 class="form_field"> Body</h4>
    			<%= f.text_area :body, class: "book_body" %>

    			<br><%= f.submit 'Create Book' %>

			<% end %>
	</body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<mata charset = "UTF-8">
		<title> 4-8</title>
		<%= stylesheet_link_tag "application", :media => "all" %>
	</head>

  	<body>
    	<p id="notice">successfully!</p>

		<p>
  			<strong>Title:</strong>
  			<%=@post.title %>
		</p>

		<p>
			<strong>Body:</strong>
			<%=@post.body %>
		</p>

		<%= link_to "Edit", edit_post_path(@post.id), class: "edit_#{@post.id}" %> |
		<%= link_to "Back", posts_path(@post.id), class: "back" %>

  	</body>
</html>

app/views/posts/top.html.erb
<!DOCTYPE html>
<html>
	<head>
		<mata charset = "UTF-8">
		<title> 4-8</title>
    	<%= stylesheet_link_tag "application", :media => "all" %>
	</head>

	<body>
		<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
		<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p>
		<p>印象を共有し交換することができます</p>
		<p><a href="/index">start</a></p>
	</body>
</html>